apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: 852856666844.dkr.ecr.us-east-1.amazonaws.com/analytics-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secrets
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "analytics"
            - name: DB_USER
              value: "analytics_user"